version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-framework-prod"
s3_bucket = "cn-seba-aws-sam-cli-managed-default-samclisourcebucket"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=LambdaFramework Environment=production"
image_repositories = []

[development]
[development.deploy]
[development.deploy.parameters]
stack_name = "lambda-framework-dev"
s3_bucket = "cn-seba-aws-sam-cli-managed-default-samclisourcebucket"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=LambdaFramework Environment=development"
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "lambda-framework-prod"
s3_bucket = "cn-seba-aws-sam-cli-managed-default-samclisourcebucket"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=LambdaFramework Environment=production"
image_repositories = [] 